authors = [
  "Felix Krause", 
  "Zack Boll",
  ]
description = "OpenCL Alire crate based off work of https://github.com/flyx/OpenCLAda"
licenses = "MIT"
maintainers = [
"Zack Boll <zackboll@gmail.com>",
]
maintainers-logins = [
"zackboll"
]
name = "openclada"
project-files = [
"opencl.gpr",
]
tags = [
  "opencl",
  "binding",
  "graphics",
  "compute",
]
version = "0.1.0-dev"